global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "localhost:9093"

scrape_configs:

  - job_name: "prometheus"
    static_configs:
      - targets:
          - "localhost:9090"


  - job_name: "node-exporter"
    static_configs:
      - targets:
          - "localhost:9100"
          - "127.0.0.1:9100"


  - job_name: "cadvisor"
    static_configs:
      - targets:
          - "localhost:8080"

  - job_name: "docker"
    static_configs:
      - targets:
          - "localhost:9323"

  - job_name: "nginx"
    static_configs:
      - targets:
          - "localhost:9113"

  - job_name: "apache"
    static_configs:
      - targets:
          - "localhost:9117"


  - job_name: "mysql"
    static_configs:
      - targets:
          - "localhost:9104"

  - job_name: "postgresql"
    static_configs:
      - targets:
          - "localhost:9187"

  - job_name: "redis"
    static_configs:
      - targets:
          - "localhost:9121"

  - job_name: "mongodb"
    static_configs:
      - targets:
          - "localhost:9216"


  - job_name: "blackbox-http"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - "http://localhost"
          - "https://google.com"
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: "localhost:9115"
